name: Call API

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Delay for 5 minutes
        run: sleep 300

      - name: Call API 
        run: |
          response=$(curl -s -X GET https://flow.sokt.io/func/scriGyxssCRq)
          echo "$response"

