name: Call API

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          response=$(curl -s -X GET https://jsonplaceholder.typicode.com/posts)
          echo "$response"

