name: Call API

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API 
        run: |
          response=$(curl -s -X GET https://flow.sokt.io/func/scriyxIVTzG3?key=BE)
          echo "$response"

